"""empty message

Revision ID: 0d4e58d946cf
Revises: 1dd572206399
Create Date: 2022-01-30 10:47:59.114099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d4e58d946cf'
down_revision = '1dd572206399'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_history',
    sa.Column('Ticker', sa.String(length=100), nullable=False),
    sa.Column('Date', sa.String(length=50), nullable=False),
    sa.Column('Open', sa.String(length=100), nullable=True),
    sa.Column('High', sa.String(length=100), nullable=True),
    sa.Column('Low', sa.String(length=100), nullable=True),
    sa.Column('Close', sa.String(length=100), nullable=True),
    sa.Column('Adj_Close', sa.String(length=100), nullable=True),
    sa.Column('Volume', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('Ticker', 'Date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_history')
    # ### end Alembic commands ###
