"""empty message

Revision ID: 1dd572206399
Revises: 90411397ce80
Create Date: 2022-01-30 10:47:23.155435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dd572206399'
down_revision = '90411397ce80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_history', sa.Column('Ticker', sa.String(length=100), nullable=False))
    op.add_column('daily_history', sa.Column('Date', sa.String(length=50), nullable=False))
    op.add_column('daily_history', sa.Column('Open', sa.String(length=100), nullable=True))
    op.add_column('daily_history', sa.Column('High', sa.String(length=100), nullable=True))
    op.add_column('daily_history', sa.Column('Low', sa.String(length=100), nullable=True))
    op.add_column('daily_history', sa.Column('Close', sa.String(length=100), nullable=True))
    op.add_column('daily_history', sa.Column('Adj_Close', sa.String(length=100), nullable=True))
    op.add_column('daily_history', sa.Column('Volume', sa.String(length=100), nullable=True))
    op.drop_column('daily_history', 'high')
    op.drop_column('daily_history', 'close')
    op.drop_column('daily_history', 'open')
    op.drop_column('daily_history', 'volume')
    op.drop_column('daily_history', 'day')
    op.drop_column('daily_history', 'ticker')
    op.drop_column('daily_history', 'low')
    op.drop_column('daily_history', 'adj_close')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_history', sa.Column('adj_close', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('daily_history', sa.Column('low', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('daily_history', sa.Column('ticker', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('daily_history', sa.Column('day', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('daily_history', sa.Column('volume', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('daily_history', sa.Column('open', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('daily_history', sa.Column('close', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('daily_history', sa.Column('high', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('daily_history', 'Volume')
    op.drop_column('daily_history', 'Adj_Close')
    op.drop_column('daily_history', 'Close')
    op.drop_column('daily_history', 'Low')
    op.drop_column('daily_history', 'High')
    op.drop_column('daily_history', 'Open')
    op.drop_column('daily_history', 'Date')
    op.drop_column('daily_history', 'Ticker')
    # ### end Alembic commands ###
