"""empty message

Revision ID: 90411397ce80
Revises: eafed65d67a4
Create Date: 2022-01-30 10:15:24.017905

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '90411397ce80'
down_revision = 'eafed65d67a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_history', sa.Column('ticker', sa.String(length=100), nullable=False))
    op.add_column('daily_history', sa.Column('day', sa.String(length=50), nullable=False))
    op.add_column('daily_history', sa.Column('open', sa.String(length=100), nullable=True))
    op.add_column('daily_history', sa.Column('high', sa.String(length=100), nullable=True))
    op.add_column('daily_history', sa.Column('low', sa.String(length=100), nullable=True))
    op.add_column('daily_history', sa.Column('close', sa.String(length=100), nullable=True))
    op.add_column('daily_history', sa.Column('adj_close', sa.String(length=100), nullable=True))
    op.add_column('daily_history', sa.Column('volume', sa.String(length=100), nullable=True))
    op.drop_index('ix_daily_history_Date', table_name='daily_history')
    op.drop_column('daily_history', 'Volume')
    op.drop_column('daily_history', 'Low')
    op.drop_column('daily_history', 'Adj Close')
    op.drop_column('daily_history', 'High')
    op.drop_column('daily_history', 'Open')
    op.drop_column('daily_history', 'Ticker')
    op.drop_column('daily_history', 'Date')
    op.drop_column('daily_history', 'Close')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_history', sa.Column('Close', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('daily_history', sa.Column('Date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('daily_history', sa.Column('Ticker', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('daily_history', sa.Column('Open', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('daily_history', sa.Column('High', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('daily_history', sa.Column('Adj Close', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('daily_history', sa.Column('Low', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('daily_history', sa.Column('Volume', sa.BIGINT(), autoincrement=False, nullable=True))
    op.create_index('ix_daily_history_Date', 'daily_history', ['Date'], unique=False)
    op.drop_column('daily_history', 'volume')
    op.drop_column('daily_history', 'adj_close')
    op.drop_column('daily_history', 'close')
    op.drop_column('daily_history', 'low')
    op.drop_column('daily_history', 'high')
    op.drop_column('daily_history', 'open')
    op.drop_column('daily_history', 'day')
    op.drop_column('daily_history', 'ticker')
    # ### end Alembic commands ###
