"""empty message

Revision ID: eafed65d67a4
Revises: 521084d09ca1
Create Date: 2022-01-29 13:53:19.103274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eafed65d67a4'
down_revision = '521084d09ca1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_history',
    sa.Column('ticker', sa.String(length=100), nullable=False),
    sa.Column('day', sa.String(length=50), nullable=False),
    sa.Column('open', sa.String(length=100), nullable=True),
    sa.Column('high', sa.String(length=100), nullable=True),
    sa.Column('low', sa.String(length=100), nullable=True),
    sa.Column('close', sa.String(length=100), nullable=True),
    sa.Column('adj_close', sa.String(length=100), nullable=True),
    sa.Column('volume', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('ticker', 'day')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_history')
    # ### end Alembic commands ###
